// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmikifhihovkkcmdgjdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptaWtpZmhpaG92a2tjbWRnamRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MTYzNTcsImV4cCI6MjA2MjM5MjM1N30.NYOaXvE-cD3wSZ6JN6DgcBjjlT1IoBnCskDzDT1DjVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);